<h2><font color="#004D7F" size=6>Módulo 3. Estadística Descriptiva</font></h2>



<h1><font color="#004D7F" size=5>1. Introducción a Numpy</font></h1>

<br><br>
<div style="text-align: right">
<font color="#004D7F" size=3>Luisa López Vázquez</font><br>
<font color="#004D7F" size=3>Diplomado en Ciencia de Datos</font><br>

In [10]:
#Importar la libreria de numpy
import numpy as np

In [13]:
# Crear mi primer array
a = np.array([1,2,3,56,89,72,80])
print(a)

[ 1  2  3 56 89 72 80]


In [15]:
# Agregar elementos a nuestro array
nuevoArray = np.append(a,[200,600,800])
print(nuevoArray)

[  1   2   3  56  89  72  80 200 600 800]


In [4]:
# Sin argumentos devuelve escalar


In [16]:
#Crear un array de 4 elementos
np.random.rand(4)

array([0.6477343 , 0.36261448, 0.69078177, 0.06586051])

### Si queremos generar datos enteros entonces tenemos que usar la función np.random.randint, 
que admite un argumento obligatorio y dos opcionales:

In [22]:
# Crear mi array conde manera aleatoria
numeros = np.random.randint(1,100, size=200)
print(numeros)

[40 12 17 51 37 10 21 32 92  9 29 80 91 36 68  5 38 61 46 85 54  5 75 69
 80 44 37 79 69  6 80  9 22 36 75 53 19 97 54 89  2 20 14 14 51 16 56 63
 64 38 32  6 87 65 57 68 93 80 26 50 89 93  7 47 60 32 18 30  1 62 68 22
 51 82 81 80 39 19 42 42 19  6 10  4 18  2 40 16 88 37 67 95 79 21 35 22
 31  8 26 13 61 26 37  7 84 33 19 23 47 17  9 66 37 99 39 34 80 45 26 81
 83 93 13 72 79  9 83 92  9  6 34 35 85 30 22 68 96 82 93 99  9 74 93 65
 50 87 87 55 98 76 71 30 40  1 78 66 34  7 77 57  5 39 48 16 77 48  7 54
  4 55 65  3 75 33 72 60 54 97  3 85 22 10 58 20  4 61 31 59 71 11 21 89
 52 49 10 82 43 18 44  3]


In [24]:
# Crear una matriz de 3 x 3
matrix = np.random.randint(2,60, size=(3,3))
print(matrix)

[[18 48 52]
 [50 43 56]
 [31 23 26]]


### Utilice la función numpy.random.uniform() para generar números flotantes aleatorios en Python

In [27]:
#Generar 10 números flotantes en el rango de números del 0 al 6.
random_numbers = np.random.uniform(low=20,high=60, size=10).tolist()
print(random_numbers)

[40.564697375686364, 40.109121312055954, 37.498447610494765, 31.4635546914646, 24.880150991745815, 42.068611009111265, 30.60602385384296, 58.99486278150502, 54.84169819059672, 29.362550566141312]


In [28]:
#Crear un progrma que nos pregunte cuantos numeros aleatorios queremos generar
import random
def listaAleatorios(n):
      lista = [0]  * n
      for i in range(n):
          lista[i] = random.randint(0, 1000)
      return lista

print("Ingrese cuantos numeros aleatorios desea obtener")
n=int(input())

aleatorios=listaAleatorios(n)
print(aleatorios)

Ingrese cuantos numeros aleatorios desea obtener


 100


[115, 744, 484, 420, 478, 567, 270, 170, 424, 519, 855, 267, 762, 96, 608, 543, 301, 95, 320, 432, 887, 534, 813, 697, 143, 707, 920, 440, 146, 45, 62, 143, 177, 537, 414, 416, 760, 546, 294, 190, 960, 568, 173, 667, 129, 779, 608, 91, 282, 765, 802, 830, 160, 381, 851, 538, 644, 82, 46, 963, 841, 127, 841, 485, 467, 959, 861, 259, 712, 714, 783, 865, 27, 782, 247, 714, 867, 82, 846, 194, 113, 421, 89, 674, 814, 484, 582, 816, 983, 130, 486, 86, 462, 631, 525, 321, 57, 587, 1000, 158]
